apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config
  namespace: technitium
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path      # standaard k3s StorageClass
  resources:
    requests:
      storage: 2Gi
