apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ontwikkel
resources:
- ../../base
# CI (kustomize edit set image) schrijft hier de git-sha van de laatste build:
images:
- name: ghcr.io/alexverstappen83/bc-doelen-backend
  newName: ghcr.io/alexverstappen83/bc-doelen-backend
  newTag: d082bb70afa27cad2c67e3b08da6f2a4fd872746
- name: ghcr.io/alexverstappen83/bc-doelen-frontend
  newName: ghcr.io/alexverstappen83/bc-doelen-frontend
  newTag: d082bb70afa27cad2c67e3b08da6f2a4fd872746
  # per-omgeving config (CORS/redirect naar de ontwikkel-host)
  # ingress-host voor ontwikkel
patches:
- path: patch-config.yaml
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: bcdoelen.ontwikkel.brightcubes.ai
  target:
    kind: Ingress
    name: bc-doelen
